
# openssl genrsa -out jredmine.forsrc.com.key 2048
# openssl req -new -x509 -key jredmine.forsrc.com.key -out jredmine.forsrc.com.crt -subj /C=CN/OU=jredmine.forsrc.com/L=sh/ST=forsrc/CN=jredmine.forsrc.com


# keytool -genkeypair -alias forsrc -keyalg RSA -keysize 4096 -keystore forsrc.p12 -storepass forsrc -storetype pkcs12 -validity 10 -dname "CN=jredmine.forsrc.com, OU=Example, O=Curity AB, C=CN"

# keytool -export -alias forsrc -keystore forsrc.p12 -storepass forsrc -file forsrc.cer

# kubectl create secret tls jredmine.forsrc.com -n jredmine --cert=jredmine.forsrc.com.crt --key=jredmine.forsrc.com.key



apiVersion: v1
kind: Secret
metadata:
  name: jredmine.forsrc.com
  namespace: jredmine
type: kubernetes.io/tls
data:
  # cat forsrc.cer | base64
  tls.crt: |
    MIIDrzCCApegAwIBAgIUKejd/D0oq1l7jqiLYzq1tBxVEmMwDQYJKoZIhvcNAQEL
    BQAwZzELMAkGA1UEBhMCQ04xHDAaBgNVBAsME2pyZWRtaW5lLmZvcnNyYy5jb20x
    CzAJBgNVBAcMAnNoMQ8wDQYDVQQIDAZmb3JzcmMxHDAaBgNVBAMME2pyZWRtaW5l
    LmZvcnNyYy5jb20wHhcNMjIwMTMxMDUxMTIwWhcNMjIwMzAyMDUxMTIwWjBnMQsw
    CQYDVQQGEwJDTjEcMBoGA1UECwwTanJlZG1pbmUuZm9yc3JjLmNvbTELMAkGA1UE
    BwwCc2gxDzANBgNVBAgMBmZvcnNyYzEcMBoGA1UEAwwTanJlZG1pbmUuZm9yc3Jj
    LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALP7+vj5vlEBiT41
    fXrUv7osOh8NGDNLlY+vNn8XfI13h/PjG7XsXoEZl+n8K85kEcxATEXf1Av15bgZ
    +zt3AMNMa9WQ2ZGQSieDEH5ud4lZpc6I9ZHx+wkL9M5r776+4LOqYITVNnaBXccO
    MJe0cZ1LyUw00QUmb3jfHoEGGE0xi4UG6t+UU/WY+RFjQSh7ELsMeHiAwIXDxHhe
    HNDbf5DkRj5q87X5ImM7o0EchFOmNSN62Ld9SzQeT1aTtVGUNc5K/w2GMqvKo6JA
    ZaeMzFBZtUEfOZa8hf8IOvK1+19K47hxiuyqRMvDjWr7QKv5RNo0weyQjry8tZG+
    oyd+5XECAwEAAaNTMFEwHQYDVR0OBBYEFKQgiXgZ939Y65xB90qSxu/nt/JoMB8G
    A1UdIwQYMBaAFKQgiXgZ939Y65xB90qSxu/nt/JoMA8GA1UdEwEB/wQFMAMBAf8w
    DQYJKoZIhvcNAQELBQADggEBADZCMK7oPnAui+Cw6LWr8opo1dWUgHoNrOA2LY9R
    1eTi/zlBP4+S7WrSuZj4xkmFsz7T7uSWzGoaoXUBALmVevwVLiK6fUf5/jguLXjY
    z7SGHWun4s8vlNNATrfKLdHOB5Tj9eg+E9ZZpUmMxP9f3FSrH0S6Wn+P4wWkV8F+
    zRyC8+V+SfMOiUOMf2SzXczRacypmM0ORHirI4ZVRc3nCPEnxNxsdQORoHs3cNEB
    paJuwxeOoVb4SU2kJsTKNxgOZ5s54RARSSUymBbDpUTvNhbzco+Y56JoM1x1Bie4
    k15ysmv4H/I3qG5m+dwqVj0FW++Jv0EHh5OrpM8XEpmxZ4E=
  # cat forsrc.p12 | base64
  tls.key:  |
    MIIEpAIBAAKCAQEAs/v6+Pm+UQGJPjV9etS/uiw6Hw0YM0uVj682fxd8jXeH8+Mb
    texegRmX6fwrzmQRzEBMRd/UC/XluBn7O3cAw0xr1ZDZkZBKJ4MQfm53iVmlzoj1
    kfH7CQv0zmvvvr7gs6pghNU2doFdxw4wl7RxnUvJTDTRBSZveN8egQYYTTGLhQbq
    35RT9Zj5EWNBKHsQuwx4eIDAhcPEeF4c0Nt/kORGPmrztfkiYzujQRyEU6Y1I3rY
    t31LNB5PVpO1UZQ1zkr/DYYyq8qjokBlp4zMUFm1QR85lryF/wg68rX7X0rjuHGK
    7KpEy8ONavtAq/lE2jTB7JCOvLy1kb6jJ37lcQIDAQABAoIBAFi4IAl0igTCPhWl
    JlpS3sN1o5zExqYaXvn5w2I4gJP3VNO6omE1x4vZwtF7FVjiaQeGtlJHN+5BYuAy
    Jm40hfK/C/S1NxoSxwrdB1dbOp9AyoOZbXtojXbzJtRNzlr3GipWFMfFldgqgsBp
    VTiioNKJlgtziYkBXjd1vEKbb4U00EjEpDsxnGtAM8IgdwON4EV4KwinHrHSocAK
    eyHWkAE7KMviPcj8WqV8U+pm8plp2RtbuExKtSxE5RAhlXsH/3wjHHB4p6it/gZG
    1p9kc2jUUMYUgu2AnrY9aLBpacKJUu2s/vuvg10rY5aUcKTGXQIoLFsjKc1dLzoJ
    I2gpE6UCgYEA2vzxTSw7Xr/Bj7jrxqflLQLAjiQwPWWqguokwuA6kBRDVWvW0sl2
    XH3WFHyPo2JTHH8WocCgMryJSlthi0WyEL9bp5gMfQYzse02vYjO1mEHat+gYKkt
    8wcynOqq8bbSD0ZASEJVAkNUSV6bkvLfY8EoKuKyH04H9rj0WQt+Nt8CgYEA0mdx
    ssftuBUBZTDHeZU4wS6tPV0Fs9RivDJ/F9z6d6eV/y5uTMCXohYwGJWZUfFYRlVA
    S7nwtn9AoQ+3F6YbCdIkP65NEeqtjA7QrDMJOI/DL4mbXhMlckXZknqdQjkuGTLi
    aiXI0GpIswfhXmO0+o4Xl9AMP0NqLfI3iGCj/a8CgYEAznwAfvb9CCshNQZ1crxu
    8JEOxThEMDBDpetnPEU3kxE4KDxltB14OGAC0xBcU/9rRIxk56H8q7pwbadag3r1
    GquEnbNV2zFU3ylAG1j7RtL4roIr89ix1dzskV8ITqBG01Y3WKsLAvY/bGsDoHzX
    vHSuDjnxIGlwQuhEpg2bNdsCgYEAlTMnjBh7+OJkV+ZMPWpUkaDQ1kfFiGzeCwhf
    2YMo1XqwQgEh1ClqHVVQi85hp5rV9yHy8wAKss7v/IZRVmLCn6c1bzbhjgf1QvEq
    hkG2kzZWuboBw6ceEbd4foeWRmSXzOSpa44ZpbkIjnPTG4TmzBnAnzW3yZC7lZNC
    T+H/yB8CgYAUQmp+2rJ7RXWJauoHDHAnAg6XYzkL1eLMHmjfGTBKB0v1rq2b13kY
    CXNhm922bHPeIie6U8SsobS/yLD+uCqCg1uxiakfaX0IAgWOLNFYwAjSsX+Vs8gc
    FrZfC9M0po4+SG2Yk0uC4ZXeVli0itSRHGTEwll7zxrJADy4e3de9w==
